# 01 Data Cleaning Notebook
This notebook demonstrates the extraction, transformation, and ingestion steps of the ETL pipeline. It imports functions from the `src/` modules.

In [1]:
import os
import sys
sys.path.append(os.path.abspath('..'))

from src.extract import extract_data
from src.transform import transform_data
from src.database import get_db_engine
from src.load import load_data

In [2]:
df_raw = extract_data()
df_raw.head()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [3]:
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order Id          9994 non-null   int64
 1   Order Date        9994 non-null   str
 2   Ship Mode         9988 non-null   str
 3   Segment           9994 non-null   str
 4   Country           9994 non-null   str
 5   City              9994 non-null   str
 6   State             9994 non-null   str
 7   Postal Code       9994 non-null   int64
 8   Region            9994 non-null   str
 9   Category          9994 non-null   str
 10  Sub Category      9994 non-null   str
 11  Product Id        9994 non-null   str
 12  cost price        9994 non-null   int64
 13  List Price        9994 non-null   int64
 14  Quantity          9994 non-null   int64
 15  Discount Percent  9994 non-null   int64
dtypes: int64(6), str(10)
memory usage: 1.2 MB

In [4]:
df_clean = transform_data(df_raw)
df_clean.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0

In [5]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      9994 non-null   int64
 1   order_date    9994 non-null   datetime64[us]
 2   ship_mode     9988 non-null   str
 3   segment       9994 non-null   str
 4   country       9994 non-null   str
 5   city          9994 non-null   str
 6   state         9994 non-null   str
 7   postal_code   9994 non-null   int64
 8   region        9994 non-null   str
 9   category      9994 non-null   str
 10  sub_category  9994 non-null   str
 11  product_id    9994 non-null   str
 12  quantity      9994 non-null   int64
 13  discount      9994 non-null   float64
 14  sale_price    9994 non-null   float64
 15  profit        9994 non-null   float64
dtypes: datetime64[us](1), float64(3), int64(3), str(9)
memory usage: 1.2 MB

In [6]:
engine = get_db_engine()
load_data(df_clean, engine)