In [1]:
!pip install kaggle
import kaggle

Requirement already satisfied: kaggle in C:\Users\piyus\OneDrive\Desktop\ML\LR\venv\Lib\site-packages (2.0.0)
Requirement already satisfied: bleach in C:\Users\piyus\OneDrive\Desktop\ML\LR\venv\Lib\site-packages (from kaggle) (6.3.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.15 in C:\Users\piyus\OneDrive\Desktop\ML\LR\venv\Lib\site-packages (from kaggle) (0.1.15)
Requirement already satisfied: packaging in C:\Users\piyus\OneDrive\Desktop\ML\LR\venv\Lib\site-packages (from kaggle) (26.0)
Requirement already satisfied: protobuf in C:\Users\piyus\OneDrive\Desktop\ML\LR\venv\Lib\site-packages (from kaggle) (6.33.5)
Requirement already satisfied: python-dateutil in C:\Users\piyus\OneDrive\Desktop\ML\LR\venv\Lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in C:\Users\piyus\OneDrive\Desktop\ML\LR\venv\Lib\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in C:\Users\piyus\OneDrive\Desktop\ML\LR\venv\Lib\site-packages (from kaggle) (2.32.5)
Requirement already satisfied: tqdm in C:\Users\piyus\OneDrive\Desktop\ML\LR\venv\Lib\site-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in C:\Users\piyus\OneDrive\Desktop\ML\LR\venv\Lib\site-packages (from kaggle) (2.6.3)
Requirement already satisfied: webencodings in C:\Users\piyus\OneDrive\Desktop\ML\LR\venv\Lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: six>=1.5 in C:\Users\piyus\OneDrive\Desktop\ML\LR\venv\Lib\site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in C:\Users\piyus\OneDrive\Desktop\ML\LR\venv\Lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\piyus\OneDrive\Desktop\ML\LR\venv\Lib\site-packages (from requests->kaggle) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\piyus\OneDrive\Desktop\ML\LR\venv\Lib\site-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\piyus\OneDrive\Desktop\ML\LR\venv\Lib\site-packages (from requests->kaggle) (2026.1.4)
Requirement already satisfied: colorama in C:\Users\piyus\OneDrive\Desktop\ML\LR\venv\Lib\site-packages (from tqdm->kaggle) (0.4.6)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.0), please consider upgrading to the latest version (2.0.2)
Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
Downloading orders.csv.zip to C:\Users\piyus\OneDrive\Desktop\ML\LR\data-analytics

  0%|          | 0.00/200k [00:00<?, ?B/s]
100%|##########| 200k/200k [00:01<00:00, 152kB/s]
100%|##########| 200k/200k [00:01<00:00, 152kB/s]

In [3]:
#extract file from zip file
import zipfile
zip_ref = zipfile.ZipFile('orders.csv.zip') 
zip_ref.extractall() # extract file to dir
zip_ref.close() # close file

In [4]:
import pandas as pd
df = pd.read_csv('orders.csv',na_values=['Not Available','unknown'])
df['Ship Mode'].unique()
df.head()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [5]:
#rename columns names ..make them lower case and replace space with underscore
df.rename(columns={'Order Id':'order_id', 'City':'city'})
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [6]:
#derive new columns discount , sale price and profit
df['discount']=df['list_price']*df['discount_percent']*.01
df['sale_price']= df['list_price']-df['discount']
df['profit']=df['sale_price']-df['cost_price']
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [7]:
#convert order date from object data type to datetime
df['order_date']=pd.to_datetime(df['order_date'],format="%Y-%m-%d")

In [8]:
#drop cost price list price and discount percent columns
df.drop(columns=['list_price','cost_price','discount_percent'],inplace=True)

In [9]:
#load the data into sql server using replace option
!pip install pymysql

Requirement already satisfied: pymysql in C:\Users\piyus\OneDrive\Desktop\ML\LR\venv\Lib\site-packages (1.1.2)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
import sys
!{sys.executable} -m pip install cryptography

Requirement already satisfied: cryptography in C:\Users\piyus\OneDrive\Desktop\ML\LR\venv\Lib\site-packages (46.0.5)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\piyus\OneDrive\Desktop\ML\LR\venv\Lib\site-packages (from cryptography) (2.0.0)
Requirement already satisfied: pycparser in C:\Users\piyus\OneDrive\Desktop\ML\LR\venv\Lib\site-packages (from cffi>=2.0.0->cryptography) (3.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
import sqlalchemy as sal

engine = sal.create_engine(
    "mysql+pymysql://root:161975@localhost:3306/salesdb"
)

conn = engine.connect()
print("Connected Successfully!")

Connected Successfully!

In [12]:
df.to_sql('df_orders', con=engine, index=False, if_exists='replace')

print("Data uploaded successfully!")

Data uploaded successfully!

In [13]:
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0

In [14]:
df = pd.read_sql("SELECT * FROM df_orders", engine)
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0

In [15]:
query1 = """
SELECT product_id,
       SUM(sale_price) AS sales
FROM df_orders
GROUP BY product_id
ORDER BY sales DESC
LIMIT 10
"""

df_top = pd.read_sql(query1, engine)
df_top

        product_id    sales
0  TEC-CO-10004722  59514.0
1  OFF-BI-10003527  26525.3
2  TEC-MA-10002412  21734.4
3  FUR-CH-10002024  21096.2
4  OFF-BI-10001359  19090.2
5  OFF-BI-10000545  18249.0
6  TEC-CO-10001449  18151.2
7  TEC-MA-10001127  17906.4
8  OFF-BI-10004995  17354.8
9  OFF-SU-10000151  16325.8

In [16]:
query2 = """
WITH cte AS (
    SELECT 
        region,
        product_id,
        SUM(sale_price) AS sales
    FROM df_orders
    GROUP BY region, product_id
)
SELECT *
FROM (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY region ORDER BY sales DESC) AS rn
    FROM cte
) A
WHERE rn <= 5;
"""

df_top_products = pd.read_sql(query2, engine)
print("Top products by region:")
display(df_top_products)

Top products by region:

     region       product_id    sales  rn
0   Central  TEC-CO-10004722  16975.0   1
1   Central  TEC-MA-10000822  13770.0   2
2   Central  OFF-BI-10001120  11056.5   3
3   Central  OFF-BI-10000545  10132.7   4
4   Central  OFF-BI-10004995   8416.1   5
5      East  TEC-CO-10004722  29099.0   1
6      East  TEC-MA-10001047  13767.0   2
7      East  FUR-BO-10004834  11274.1   3
8      East  OFF-BI-10001359   8463.6   4
9      East  TEC-CO-10001449   8316.0   5
10    South  TEC-MA-10002412  21734.4   1
11    South  TEC-MA-10001127  11116.4   2
12    South  OFF-BI-10001359   8053.2   3
13    South  TEC-MA-10004125   7840.0   4
14    South  OFF-BI-10003527   7391.4   5
15     West  TEC-CO-10004722  13440.0   1
16     West  OFF-SU-10000151  12592.3   2
17     West  FUR-CH-10001215   9604.0   3
18     West  OFF-BI-10003527   7804.8   4
19     West  TEC-AC-10003832   7722.7   5

In [17]:
query3 = """
WITH cte AS (
    SELECT 
        YEAR(order_date) AS order_year,
        MONTH(order_date) AS order_month,
        SUM(sale_price) AS sales
    FROM df_orders
    GROUP BY YEAR(order_date), MONTH(order_date)
)
SELECT 
    order_month,
    SUM(CASE WHEN order_year = 2022 THEN sales ELSE 0 END) AS sales_2022,
    SUM(CASE WHEN order_year = 2023 THEN sales ELSE 0 END) AS sales_2023
FROM cte
GROUP BY order_month
ORDER BY order_month;
"""

df_mom = pd.read_sql(query3, engine)
print("Month-over-month comparison:")
display(df_mom)

Month-over-month comparison:

    order_month  sales_2022  sales_2023
0             1     94712.5     88632.6
1             2     90091.0    128124.2
2             3     80106.0     82512.3
3             4     95451.6    111568.6
4             5     79448.3     86447.9
5             6     94170.5     68976.5
6             7     78652.2     90563.8
7             8    104808.0     87733.6
8             9     79142.2     76658.6
9            10    118912.7    121061.5
10           11     84225.3     75432.8
11           12     95869.9    102556.1

In [18]:
query4 = """
WITH cte AS (
    SELECT 
        category,
        DATE_FORMAT(order_date, '%%Y%%m') AS order_year_month,
        SUM(sale_price) AS sales
    FROM df_orders
    GROUP BY category, DATE_FORMAT(order_date, '%%Y%%m')
)
SELECT *
FROM (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY sales DESC) AS rn
    FROM cte
) A
WHERE rn = 1;
"""

df_best_month = pd.read_sql(query4, engine)
display(df_best_month)

          category order_year_month    sales  rn
0        Furniture           202210  42888.9   1
1  Office Supplies           202302  44118.5   1
2       Technology           202310  53000.1   1

In [19]:
query4 = """
WITH cte AS (
    SELECT 
        sub_category,
        YEAR(order_date) AS order_year,
        SUM(sale_price) AS sales
    FROM df_orders
    GROUP BY sub_category, YEAR(order_date)
),
cte2 AS (
    SELECT 
        sub_category,
        SUM(CASE WHEN order_year = 2022 THEN sales ELSE 0 END) AS sales_2022,
        SUM(CASE WHEN order_year = 2023 THEN sales ELSE 0 END) AS sales_2023
    FROM cte
    GROUP BY sub_category
)
SELECT *,
       (sales_2023 - sales_2022) AS growth
FROM cte2
ORDER BY growth DESC
LIMIT 1;
"""

df_growth = pd.read_sql(query4, engine)
print("Highest growth sub-category:")
display(df_growth)

Highest growth sub-category:

  sub_category  sales_2022  sales_2023   growth
0     Machines     73723.2    109178.5  35455.3